apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: backend-replicaset
  namespace: itong-noufename
spec:
  replicas: 2
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
        - name: backend-container
          image: your-backend-image:latest
          ports:
            - containerPort: 8080
          resources:
            requests:
              cpu: "4m"
              memory: "32Mi"
          env:
            - name: DATABASE_URL
              value: "your-database-url"  # URL de la base de données
---
apiVersion: v1
kind: Service
metadata:
  name: backend-service
  namespace: itong-noufename
spec:
  selector:
    app: backend
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
  type: ClusterIP
