version: '3.8'

services:
  frontend:
    build: ./application/frontend
    ports:
      - "8080:80"

  backend:
    build: ./application/backend
    ports:
      - "5000:5000"

  consumer:
    build: ./application/consumer

  rabbitmq:
    image: rabbitmq:3.13.7-management
    ports:
      - "15672:15672"

  redis:
    image: redis:latest
    ports:
      - "6379:6379"
